package com.pd.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SAMPLE".
 */
public class Sample {

    private Long id;
    private String sampleCode;
    private String sortCode;
    private Long baseMessage_Id;

    public Sample() {
    }

    public Sample(Long id) {
        this.id = id;
    }

    public Sample(Long id, String sampleCode, String sortCode, Long baseMessage_Id) {
        this.id = id;
        this.sampleCode = sampleCode;
        this.sortCode = sortCode;
        this.baseMessage_Id = baseMessage_Id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSampleCode() {
        return sampleCode;
    }

    public void setSampleCode(String sampleCode) {
        this.sampleCode = sampleCode;
    }

    public String getSortCode() {
        return sortCode;
    }

    public void setSortCode(String sortCode) {
        this.sortCode = sortCode;
    }

    public Long getBaseMessage_Id() {
        return baseMessage_Id;
    }

    public void setBaseMessage_Id(Long baseMessage_Id) {
        this.baseMessage_Id = baseMessage_Id;
    }

}
