package com.pd.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LXXNJC_OFFLOADING".
 */
public class LxxnjcOffloading {

    private Long id;
    private String loadingGrade;
    private String loadingValue;
    private String gdnd;
    private String zzwy_A;
    private String zzwy_B;
    private String lfkd;
    private Long sample_Id;

    public LxxnjcOffloading() {
    }

    public LxxnjcOffloading(Long id) {
        this.id = id;
    }

    public LxxnjcOffloading(Long id, String loadingGrade, String loadingValue, String gdnd, String zzwy_A, String zzwy_B, String lfkd, Long sample_Id) {
        this.id = id;
        this.loadingGrade = loadingGrade;
        this.loadingValue = loadingValue;
        this.gdnd = gdnd;
        this.zzwy_A = zzwy_A;
        this.zzwy_B = zzwy_B;
        this.lfkd = lfkd;
        this.sample_Id = sample_Id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLoadingGrade() {
        return loadingGrade;
    }

    public void setLoadingGrade(String loadingGrade) {
        this.loadingGrade = loadingGrade;
    }

    public String getLoadingValue() {
        return loadingValue;
    }

    public void setLoadingValue(String loadingValue) {
        this.loadingValue = loadingValue;
    }

    public String getGdnd() {
        return gdnd;
    }

    public void setGdnd(String gdnd) {
        this.gdnd = gdnd;
    }

    public String getZzwy_A() {
        return zzwy_A;
    }

    public void setZzwy_A(String zzwy_A) {
        this.zzwy_A = zzwy_A;
    }

    public String getZzwy_B() {
        return zzwy_B;
    }

    public void setZzwy_B(String zzwy_B) {
        this.zzwy_B = zzwy_B;
    }

    public String getLfkd() {
        return lfkd;
    }

    public void setLfkd(String lfkd) {
        this.lfkd = lfkd;
    }

    public Long getSample_Id() {
        return sample_Id;
    }

    public void setSample_Id(Long sample_Id) {
        this.sample_Id = sample_Id;
    }

}
